"""Atomic generation and parsing of deployment environment configuration."""

import json
import os
from pathlib import Path
from uuid import uuid4

from app.core.config import parse_environment_file
from app.core.exceptions import InstallationError
from app.deployment.models import SetupRequest


def build_environment(request: SetupRequest) -> dict[str, str]:
    request = request.validated()
    install_dir = Path(request.installation_directory)
    printer_enabled = request.printer_preference != "none"
    return {
        "CARTHAGE_POS_DB": request.database_path,
        "POS_BUSINESS_NAME": request.business_name,
        "POS_INSTALLATION_DIRECTORY": request.installation_directory,
        "POS_DEPLOYMENT_STATE_FILE": str(install_dir / "config" / "deployment.json"),
        "POS_BACKUP_DIRECTORY": request.backup_directory,
        "POS_BACKUP_RETENTION_DAYS": "30",
        "POS_BACKUP_MAX_COUNT": "30",
        "POS_BACKUP_COMPRESSION": "true",
        "POS_BACKUP_AUTO_BEFORE_RESTORE": "true",
        "POS_BACKUP_VERIFY_AFTER_CREATE": "true",
        "POS_BACKUP_SCHEDULE": "MANUAL",
        "POS_PRINTER_ENABLED": str(printer_enabled).lower(),
        "POS_PRINTER_PROFILE": request.printer_preference if printer_enabled else "80mm",
        "POS_CURRENCY": request.currency,
        "POS_DEFAULT_TAX_RATE": str(request.tax_rate),
        "POS_TIMEZONE": request.timezone,
        "POS_API_HOST": request.api_host,
        "POS_API_PORT": str(request.api_port),
        "POS_API_SESSION_HOURS": "12",
        "POS_LOG_LEVEL": request.log_level,
        "POS_LOG_DIRECTORY": str(install_dir / "logs"),
        "POS_SEED_SAMPLE_DATA": "false",
        "POS_UPDATE_CHANNEL": "stable",
        "POS_UPDATE_MANIFEST": str(install_dir / "updates" / "manifest.json"),
        "POS_AUTO_UPDATE_CHECK": "false",
    }


def generate_environment_file(request: SetupRequest, path: str | None = None) -> dict:
    request = request.validated()
    values = build_environment(request)
    destination = Path(path or Path(request.installation_directory) / "config" / "carthage-pos.env")
    write_environment_values(values, destination)
    return {"path": str(destination), "settings": values}


def write_environment_values(values: dict[str, str], path: str | Path) -> None:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.{uuid4().hex}.tmp")
    lines = ["# Generated by Carthage POS Installer. Do not store passwords here."]
    lines.extend(f"{key}={json.dumps(value)}" for key, value in sorted(values.items()))
    try:
        temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
        os.chmod(temporary, 0o600)
        os.replace(temporary, destination)
    except OSError as exc:
        temporary.unlink(missing_ok=True)
        raise InstallationError("Application configuration could not be generated.") from exc


def validate_environment_file(path: str) -> dict[str, str]:
    return parse_environment_file(path)
